FROM debian:buster-slim
RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY ./vaultwarden_ldap/target/release/vaultwarden_ldap /vaultwarden_ldap
WORKDIR /

CMD ["/vaultwarden_ldap"]
