FROM debian:buster-slim
RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY ./bitwarden_rs_ldap/target/release/bitwarden_rs_ldap /bitwarden_rs_ldap
WORKDIR /

CMD ["/bitwarden_rs_ldap"]
